[tool.poetry]
name = "votekit"
version = "1.1.0"
description = "A Swiss Army Knife for computational social choice research"
authors = ["MGGG <engineering@mggg.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9,<3.12"
scipy = "^1.11.1"
mypy = "^1.4.1"
pydantic = "^1.10.9"
pandas-stubs = "^2.0.2.230605"
scikit-learn = "^1.3.0"
pot = "0.9.0"
networkx = "^3.1"
jinja2 = "^3.1.2"
matplotlib = "^3.7.2"
pandas = "^1.5.3"
apportionment = "^1.0"



[tool.poetry.group.dev.dependencies]
ruff = "^0.0.275"
black = "^23.3.0"
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
pre-commit = "^3.3.3"
ipython = "^8.17.2"
mkdocs = "^1.5.3"
mkdocs-autorefs = "^0.5.0"
mkdocs-click = "^0.8.1"
mkdocs-material = "^9.4.10"
mkdocs-material-extensions = "^1.3"
mkdocs-table-reader-plugin = "^2.0.3"
mkdocstrings = "^0.24.0"
mkdocstrings-python = "^1.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100

[project.urls]
repository = "https://github.com/mggg/VoteKit"
